### ISSUE TITLE
Need for Row Component to enhance row events

### ISSUE THREAD

**Issue by carlospence** [mckervinc/react-fluid-table#11]
How can one add event such as onClick to an entire row? It is possible to enhance a cell through cell component when defining the columns but nothing for the entire row.

If I want to enhance the entire row, I have to do it on each cell to complete the entire row
I created a Cell Renderer that has onClick event for all the cells but the onClick event only works for a part of the cell. I need the onClick event on the row-container or on the cell 

I think a cellWrapper or rowWrapper is needed where the entire row-container or cell-container can be enhanced by anyone for any purpose. e.g I might use the table, header, row and cell wrapper to convert my table to bootstrap table by changing the out from` <div>`  to either `<table>`, `<thead>`, `<tr>` or `<td>` and also add events on them.

**Comment by mckervinc** [comment]
@carlospence yup good find, sorry for the late response. yup that's something that I can definitely look to add in the next release! Thanks for letting me know!

**Comment by mckervinc** [comment]
Effectively, we want the ability to add events as needed without bloating the API. Furthermore, I also have to consider the functionality when row expansion is enabled on a table. I'll probably pass the event so that the user can cancel if need be.

this So I think a proposal for this would be as follows:

```
onRowClick = (e: Event) => void
```

The plan is to add more event handlers in this manner.

**Comment by mckervinc** [comment]
@carlospence This should be addressed in the current release (v0.4.0). See the [CHANGELOG](https://github.com/mckervinc/react-fluid-table/blob/master/CHANGELOG.md#040) for more details.

The next release I'll add a `cellContainer` prop on the top level for more simplicity

**Comment by carlospence** [comment]
Ok thanks, I will check it out and revert
