### ISSUE TITLE
ForwardRef to access the VariableSizeList methods

### ISSUE THREAD

**Issue by dkluhzeb** [mckervinc/react-fluid-table#13]
Your project is awesome and i would like to use it.

In my case i need to have access to the scrollToItem method of the VariableSizeList.
Is it possible to implement an forewarded ref.

Maybe something like:
```*.tsx
// Table.tsx
/**
 * The main table component
 */
const ListComponent = ({
  data,
  width,
  height,
  itemKey,
  rowHeight,
  className,
  forwardRef, // prop for forwarded ref
  ...rest
}: ListProps) => {
  // hooks
  const timeoutRef = useRef(0);
  const prevRef = useRef(width);
  const cacheRef = useRef<any>({});
  const listRef = forwardRef || useRef<any>(null); // use forwarded ref if given
```

```*.tsx
// Example

const Example1 = () => {
  const testRef = useRef(null)
  return <Table forwardRef={testRef} data={testData} columns={columns} />;
}
```

I've tried this local and it worked for me but i am new to react, so i am not sure is this causes side effects.

**Comment by mckervinc** [comment]
@dkluhzeb thanks for pointing this out! I'll take a look and see about including a reference to the underlying VariableSizeList.

Another option I may consider is to give access to the scrollToItem method itself, for simplicity's sake

**Comment by dkluhzeb** [comment]
@mckervinc thanks! 
Sure this would be a cleaner solution. More to maintain, but way more stable.

**Comment by colemars** [comment]
@mckervinc any updates here? After the `rowRenderer` and `rowStyle` updates, a ref to the List component is the last bit of functionality I would need to delete my fork🎉

**Edit:**

Actually, with customHeaders now supported I might not need the ref anymore. Will update back here once I look into it.

**Comment by mckervinc** [comment]
@dkluhzeb @colemars you should now be able to pass a ref through to the component as of version `0.4.1`.

i.e like so:
```js
const Example = () => {
  const ref = useRef(null);
  const [number, setNumber] = useState(0);
  const onSubmit = useCallback(() => ref.current.scrollToItem(number), [number]);

  return (
    <div>
      <input type="number" value={number} onChange={e => setNumber(parseInt(e.target.value)} />
      <button onClick={onSubmit}>Click here</button>
      <Table ref={ref} data={data} columns={columns} tableHeight={400} />
    </div>
  );
};
```
