### ISSUE TITLE
Table rowHeight

### ISSUE THREAD

**Issue by wot48** [mckervinc/react-fluid-table#2]
Setting rowHeight has no effect on row height.

**Comment by mckervinc** [comment]
@wot48 good point. I should make the documentation a bit clearer. So `rowHeight` actually acts more like a `defaultRowHeight`, not a fixed `rowHeight` of pixels.

I plan on adding a `fixed` prop to make the rowHeight static

**Comment by mckervinc** [comment]
@wot48 Look at the updated docs [here](https://mckervinc.github.io/react-fluid-table/#/props). Now `rowHeight` should work as expected: it explicitly sets the height of each row to be `rowHeight` pixels. Install the latest version to test.

An example of `rowHeight` being used can be found [here](https://mckervinc.github.io/react-fluid-table/#/sub). Closing the ticket. Will re-open if this becomes an issue again
