### ISSUE TITLE
How to custom column alignment ?

### ISSUE THREAD

**Issue by x4080** [mckervinc/react-fluid-table#23]
Hi, nice component. Do you have best practice to change column alignment, for number column that needs to be right aligned ?

Thanks

**Comment by AppJarBiz** [comment]
{
        key: "amount",
        header: "Gross",
        sortable: true,
        content:  ({row}) => {return(<div style={{ marginLeft:"auto", `marginRight:"0"}}>{formatCurrency(row.amount)}</div>)},`
      },

**Comment by AppJarBiz** [comment]
Since it is so common to align numbers on the right it would be great if the next version hand an alignment property on the column definition. "left" (default), "right", or "center"

**Comment by mckervinc** [comment]
@AppJarBiz agreed, I'll add that!
