### ISSUE TITLE
Possible to support min-width on rows?

### ISSUE THREAD

**Issue by colemars** [mckervinc/react-fluid-table#28]
Use case is when you want the table rows to expand all the way across the table, for example by setting the width of a column to auto, however you don't want the auto width column to shrink into nothingness when collapsing.

I haven't looked at the code so I'm not sure if this is possible or not. Any thoughts?

**Comment by mckervinc** [comment]
@colemars hmm this shouldn't happen if the auto sizer is working correctly. I'll try and reproduce the bug
