### ISSUE TITLE
Question: is there a way to prevent the table from scrolling back to the top when it is re-rendered?

### ISSUE THREAD

**Issue by andrew-mclachlan** [mckervinc/react-fluid-table#50]
Is there a way to prevent the table from scrolling back to the top when it is re-rendered?

Basically, I'm rendering the table, moving away to a different "View", and back again. The table is re-rendered with the same data, but if it's a long table, then the scroll bar goes back to the top.

Any thoughts would be greatly appreciated! Great component btw!

**Comment by mckervinc** [comment]
@andrew-mclachlan sorry for the long wait, but I can definitely look into it. I'll see if there is a way to save the scroll position between renders.

If you can, could you provide a JSFiddle or something similar so I can replicate the issue? Thanks!

**Comment by andrew-mclachlan** [comment]
Super! I'll see if I can create a small cut down example.
