### ISSUE TITLE
No support for custom columnn

### ISSUE THREAD

**Issue by MikeWarren2014** [mckervinc/react-fluid-table#7]
[Per the documentation](https://mckervinc.github.io/react-fluid-table/#/props), we can write a custom component to `colObj.header` and that component will render. However, when I do something like :

```
const ColumnHeader = (props) => { 
  console.log(props)
  return <div
    // TODO: idk what is supposed to go here
    onClick={(e) => {}}
  >
    {/* TODO: idk what goes here... */}
    {props.header}
  </div>
}

const columns = [
  { key: "ID", header: <ColumnHeader text="ID" />, scope: "col"},
  { key: "FirstName", header: <ColumnHeader text="First Name" />, scope: "col"},
  { key: "LastName", header: <ColumnHeader text="Last Name" />, scope: "col"},
  { key: "Email", header: <ColumnHeader text="Email" />, scope: "col" }
];
```

and give that `columns` to the `<Table>`, nothing renders for the columns. 

Why is this happening?

**Comment by mckervinc** [comment]
@MikeWarren2014 yea the issue here is that your columns array should look like this:
```jsx
const columns = [
  {key: "ID", header: (onClick) => <ColumnHeader text="ID" onClick={onClick}/>, scope: "col"},
  ...
]
```

But in my next update, I'll change it so all you have to do is this:
```jsx
const ColumnHeader = ({ onClick }) => { 
  return <div
    // TODO: idk what is supposed to go here
    onClick={(e) => {onClick()}}
  >
    {/* TODO: idk what goes here... */}
    {props.header}
  </div>
}

const columns = [
  {key: "ID", header: ColumnHeader, scope: "col"},
  ...
]
```

sorry for the delay in the response, the world's kind of gone to, well, ya know

**Comment by mckervinc** [comment]
@MikeWarren2014 if you look at the updated docs, you should be able to see how to do CustomHeaders. This feature is now supported :)
