### ISSUE TITLE
Sorting function is using stale data prop

### ISSUE THREAD

**Issue by HynekS** [mckervinc/react-fluid-table#8]
Hello! I was trying to replace an old _react-virtualized_ `Table` component with your module, which have a waaay cleaner API, and – unlike _react-window_ – supports fixed headers and sorting out of the box.

However, I have run into an issue with the sorting functionality:

## Expected Behavior
The sorting function sorts the actual data passed as the `data` prop.

## Actual Behavior
The sorting function populates the `Table` component with data used for an initial render. Logging of the data from sorting function shows this stale prop. To get the actual, "fresh" data, I need to reload, or navigate to a route which does not utilize `Table` component.

![StalePropsOnSort](https://user-images.githubusercontent.com/24924967/78353403-432af400-75aa-11ea-9c06-355494c455f6.gif)

## Steps to Reproduce the Problem
I have run into this issue in the context of dependency-rich app, so there were multiple suspects. However, I was able to reproduce it in a pretty minimal code sandbox:

[Code sandbox reproducing the issue](https://codesandbox.io/s/wispy-dust-4j4tc)

## Specifications

Version: npm package v. 0.3.1

**Comment by mckervinc** [comment]
Hi! Thanks for letting me know. yea it turns out the issue was that i wasn't taking into account that `onSort` could change (its the stale state issue common in hooks). I'll have a fix in my next release @HynekS

**Comment by mckervinc** [comment]
@HynekS this should be now fixed as of v 0.3.2 (the latest version is 0.3.3)

You can see the example at the following [sandbox](https://codesandbox.io/s/stoic-euclid-8svmp)
